from app import create_app, db
from app.models import Question

app = create_app()

with app.app_context():
    db.drop_all()
    db.create_all()

    # Seed Questions
    questions = [
        Question(
            text="What is the capital of Brazil?",
            correct_answer="Brasília",
            category="Capitals",
            difficulty="Hard",
        ),
        Question(
            text="What is the capital of Thailand?",
            correct_answer="Bangkok",
            category="Capitals",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the capital of Turkey?",
            correct_answer="Ankara",
            category="Capitals",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the capital of Canada?",
            correct_answer="Ottawa",
            category="Capitals",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the capital of Nigeria?",
            correct_answer="Abuja",
            category="Capitals",
            difficulty="Hard",
        ),
        Question(
            text="What is the capital of South Korea?",
            correct_answer="Seoul",
            category="Capitals",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the capital of India?",
            correct_answer="New Delhi",
            category="Capitals",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital of Mexico?",
            correct_answer="Mexico City",
            category="Capitals",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the capital of Portugal?",
            correct_answer="Lisbon",
            category="Capitals",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the capital of Egypt?",
            correct_answer="Cairo",
            category="Capitals",
            difficulty="Hard",
        ),
        Question(
            text="What is the capital of Kenya?",
            correct_answer="Nairobi",
            category="Capitals",
            difficulty="Hard",
        ),
        Question(
            text="What is the capital of Norway?",
            correct_answer="Oslo",
            category="Capitals",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital of Peru?",
            correct_answer="Lima",
            category="Capitals",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the capital of Vietnam?",
            correct_answer="Hanoi",
            category="Capitals",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the capital of Saudi Arabia?",
            correct_answer="Riyadh",
            category="Capitals",
            difficulty="Hard",
        ),
        Question(
            text="What is the capital of Ireland?",
            correct_answer="Dublin",
            category="Capitals",
            difficulty="Hard",
        ),
        Question(
            text="What is the capital of Chile?",
            correct_answer="Santiago",
            category="Capitals",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the capital of New Zealand?",
            correct_answer="Wellington",
            category="Capitals",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the capital of Singapore?",
            correct_answer="Singapore",
            category="Capitals",
            difficulty="Hard",
        ),
        Question(
            text="What is the capital of the United Arab Emirates?",
            correct_answer="Abu Dhabi",
            category="Capitals",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the capital of Ghana?",
            correct_answer="Accra",
            category="Capitals",
            difficulty="Hard",
        ),
        Question(
            text="What is the capital of Sweden?",
            correct_answer="Stockholm",
            category="Capitals",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the capital of Iran?",
            correct_answer="Tehran",
            category="Capitals",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital of Ukraine?",
            correct_answer="Kyiv",
            category="Capitals",
            difficulty="Hard",
        ),
        Question(
            text="What is the capital of Argentina?",
            correct_answer="Buenos Aires",
            category="Capitals",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital of Ethiopia?",
            correct_answer="Addis Ababa",
            category="Capitals",
            difficulty="Hard",
        ),
        Question(
            text="What is the capital of Morocco?",
            correct_answer="Rabat",
            category="Capitals",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital of the Philippines?",
            correct_answer="Manila",
            category="Capitals",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the capital of Pakistan?",
            correct_answer="Islamabad",
            category="Capitals",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital of Venezuela?",
            correct_answer="Caracas",
            category="Capitals",
            difficulty="Hard",
        ),
        Question(
            text="What is the capital of Belgium?",
            correct_answer="Brussels",
            category="Capitals",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital of Tanzania?",
            correct_answer="Dodoma",
            category="Capitals",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the capital of Malaysia?",
            correct_answer="Kuala Lumpur",
            category="Capitals",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the capital of Afghanistan?",
            correct_answer="Kabul",
            category="Capitals",
            difficulty="Hard",
        ),
        Question(
            text="What is the capital of Lebanon?",
            correct_answer="Beirut",
            category="Capitals",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital of Bangladesh?",
            correct_answer="Dhaka",
            category="Capitals",
            difficulty="Hard",
        ),
        Question(
            text="What is the capital of Czech Republic?",
            correct_answer="Prague",
            category="Capitals",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the capital of Uganda?",
            correct_answer="Kampala",
            category="Capitals",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the capital of Israel?",
            correct_answer="Jerusalem",
            category="Capitals",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital of Hungary?",
            correct_answer="Budapest",
            category="Capitals",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital of Colombia?",
            correct_answer="Bogotá",
            category="Capitals",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital of Belarus?",
            correct_answer="Minsk",
            category="Capitals",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the capital of Myanmar?",
            correct_answer="Naypyidaw",
            category="Capitals",
            difficulty="Hard",
        ),
        Question(
            text="What is the capital of Iceland?",
            correct_answer="Reykjavik",
            category="Capitals",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital of South Africa?",
            correct_answer="Pretoria",
            category="Capitals",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the capital of Nepal?",
            correct_answer="Kathmandu",
            category="Capitals",
            difficulty="Hard",
        ),
        Question(
            text="What is the capital of France?",
            correct_answer="Paris",
            category="Capitals",
            difficulty="Hard",
        ),
        Question(
            text="What is the capital of Indonesia?",
            correct_answer="Jakarta",
            category="Capitals",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the capital of Russia?",
            correct_answer="Moscow",
            category="Capitals",
            difficulty="Hard",
        ),
        Question(
            text="What is the capital of Australia?",
            correct_answer="Canberra",
            category="Capitals",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital of Finland?",
            correct_answer="Helsinki",
            category="Capitals",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the capital of Switzerland?",
            correct_answer="Bern",
            category="Capitals",
            difficulty="Hard",
        ),
        Question(
            text="What is the capital of Zambia?",
            correct_answer="Lusaka",
            category="Capitals",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the capital of Panama?",
            correct_answer="Panama City",
            category="Capitals",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital of Jordan?",
            correct_answer="Amman",
            category="Capitals",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital of Fiji?",
            correct_answer="Suva",
            category="Capitals",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital of Angola?",
            correct_answer="Luanda",
            category="Capitals",
            difficulty="Hard",
        ),
        Question(
            text="What is the capital of Bolivia?",
            correct_answer="Sucre",
            category="Capitals",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the capital of Cambodia?",
            correct_answer="Phnom Penh",
            category="Capitals",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the capital of Tunisia?",
            correct_answer="Tunis",
            category="Capitals",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital of Libya?",
            correct_answer="Tripoli",
            category="Capitals",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital of Bahrain?",
            correct_answer="Manama",
            category="Capitals",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital of Laos?",
            correct_answer="Vientiane",
            category="Capitals",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital of Georgia (country)?",
            correct_answer="Tbilisi",
            category="Capitals",
            difficulty="Hard",
        ),
        Question(
            text="What is the capital of Mongolia?",
            correct_answer="Ulaanbaatar",
            category="Capitals",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the capital of the Maldives?",
            correct_answer="Malé",
            category="Capitals",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital of Lithuania?",
            correct_answer="Vilnius",
            category="Capitals",
            difficulty="Hard",
        ),
        Question(
            text="What is the capital of Paraguay?",
            correct_answer="Asunción",
            category="Capitals",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital of Albania?",
            correct_answer="Tirana",
            category="Capitals",
            difficulty="Hard",
        ),
        Question(
            text="What is the capital of Cyprus?",
            correct_answer="Nicosia",
            category="Capitals",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital of Slovakia?",
            correct_answer="Bratislava",
            category="Capitals",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the capital of Syria?",
            correct_answer="Damascus",
            category="Capitals",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital of Uzbekistan?",
            correct_answer="Tashkent",
            category="Capitals",
            difficulty="Hard",
        ),
        Question(
            text="What is the capital of Ecuador?",
            correct_answer="Quito",
            category="Capitals",
            difficulty="Intermediate",
        ),
        Question(
            text="Where is the Eiffel Tower located?",
            correct_answer="France",
            category="Famous Landmarks",
            difficulty="Hard",
        ),
        Question(
            text="In which country is the Colosseum located?",
            correct_answer="Italy",
            category="Famous Landmarks",
            difficulty="Intermediate",
        ),
        Question(
            text="What city is home to the Statue of Liberty?",
            correct_answer="New York, USA",
            category="Famous Landmarks",
            difficulty="Hard",
        ),
        Question(
            text="Where can you find the Great Wall?",
            correct_answer="China",
            category="Famous Landmarks",
            difficulty="Intermediate",
        ),
        Question(
            text="In which country is Machu Picchu located?",
            correct_answer="Peru",
            category="Famous Landmarks",
            difficulty="Hard",
        ),
        Question(
            text="Where would you find the Taj Mahal?",
            correct_answer="India",
            category="Famous Landmarks",
            difficulty="Easy",
        ),
        Question(
            text="What country is home to the ancient city of Petra?",
            correct_answer="Jordan",
            category="Famous Landmarks",
            difficulty="Hard",
        ),
        Question(
            text="Where is Stonehenge located?",
            correct_answer="England, United Kingdom",
            category="Famous Landmarks",
            difficulty="Intermediate",
        ),
        Question(
            text="In which city would you find the Burj Khalifa?",
            correct_answer="Dubai, UAE",
            category="Famous Landmarks",
            difficulty="Hard",
        ),
        Question(
            text="Which landmark is located on Easter Island?",
            correct_answer="Moai statues",
            category="Famous Landmarks",
            difficulty="Intermediate",
        ),
        Question(
            text="Where can you find the Sydney Opera House?",
            correct_answer="Australia",
            category="Famous Landmarks",
            difficulty="Easy",
        ),
        Question(
            text="Which country is home to the Acropolis?",
            correct_answer="Greece",
            category="Famous Landmarks",
            difficulty="Hard",
        ),
        Question(
            text="Where is Mount Rushmore located?",
            correct_answer="USA",
            category="Famous Landmarks",
            difficulty="Easy",
        ),
        Question(
            text="In which country is the Leaning Tower of Pisa?",
            correct_answer="Italy",
            category="Famous Landmarks",
            difficulty="Hard",
        ),
        Question(
            text="Where is the Cristo Redentor statue located?",
            correct_answer="Brazil",
            category="Famous Landmarks",
            difficulty="Easy",
        ),
        Question(
            text="Which country is known for the Red Square and Kremlin?",
            correct_answer="Russia",
            category="Famous Landmarks",
            difficulty="Hard",
        ),
        Question(
            text="Where can you find the Sagrada Familia basilica?",
            correct_answer="Spain",
            category="Famous Landmarks",
            difficulty="Intermediate",
        ),
        Question(
            text="What country is home to Neuschwanstein Castle?",
            correct_answer="Germany",
            category="Famous Landmarks",
            difficulty="Intermediate",
        ),
        Question(
            text="In which city is Big Ben located?",
            correct_answer="London, United Kingdom",
            category="Famous Landmarks",
            difficulty="Intermediate",
        ),
        Question(
            text="Where are the Pyramids of Giza located?",
            correct_answer="Egypt",
            category="Famous Landmarks",
            difficulty="Hard",
        ),
        Question(
            text="What colors are on the flag of France?",
            correct_answer="Blue, white, and red",
            category="Country Flags",
            difficulty="Easy",
        ),
        Question(
            text="Which country’s flag is red with a white cross?",
            correct_answer="Switzerland",
            category="Country Flags",
            difficulty="Intermediate",
        ),
        Question(
            text="What animal appears on the Mexican flag?",
            correct_answer="Eagle",
            category="Country Flags",
            difficulty="Intermediate",
        ),
        Question(
            text="What are the colors of the German flag?",
            correct_answer="Black, red, and yellow",
            category="Country Flags",
            difficulty="Intermediate",
        ),
        Question(
            text="Which country’s flag is known as the Union Jack?",
            correct_answer="United Kingdom",
            category="Country Flags",
            difficulty="Easy",
        ),
        Question(
            text="What colors are on the flag of Brazil?",
            correct_answer="Green, yellow, blue, and white",
            category="Country Flags",
            difficulty="Intermediate",
        ),
        Question(
            text="Which country has a maple leaf on its flag?",
            correct_answer="Canada",
            category="Country Flags",
            difficulty="Easy",
        ),
        Question(
            text="What colors are on the Italian flag?",
            correct_answer="Green, white, and red",
            category="Country Flags",
            difficulty="Intermediate",
        ),
        Question(
            text="Which African country has a red, green, and yellow flag with a black star?",
            correct_answer="Ghana",
            category="Country Flags",
            difficulty="Hard",
        ),
        Question(
            text="Which country’s flag is red with a single white circle?",
            correct_answer="Japan",
            category="Country Flags",
            difficulty="Easy",
        ),
        Question(
            text="What symbol is on the flag of Turkey?",
            correct_answer="Crescent and star",
            category="Country Flags",
            difficulty="Intermediate",
        ),
        Question(
            text="What colors are on the flag of Argentina?",
            correct_answer="Blue, white, and yellow",
            category="Country Flags",
            difficulty="Easy",
        ),
        Question(
            text="Which Middle Eastern country has a cedar tree on its flag?",
            correct_answer="Lebanon",
            category="Country Flags",
            difficulty="Intermediate",
        ),
        Question(
            text="What colors are on the flag of India?",
            correct_answer="Orange, white, green, and blue",
            category="Country Flags",
            difficulty="Easy",
        ),
        Question(
            text="What colors are on the South African flag?",
            correct_answer="Green, yellow, black, white, red, and blue",
            category="Country Flags",
            difficulty="Hard",
        ),
        Question(
            text="Which Scandinavian country's flag is blue with a yellow cross?",
            correct_answer="Sweden",
            category="Country Flags",
            difficulty="Intermediate",
        ),
        Question(
            text="What colors are on the flag of Australia?",
            correct_answer="Blue, white, and red",
            category="Country Flags",
            difficulty="Hard",
        ),
        Question(
            text="Which Caribbean country has a trident on its flag?",
            correct_answer="Barbados",
            category="Country Flags",
            difficulty="Intermediate",
        ),
        Question(
            text="Which country has a flag that’s just one solid green color?",
            correct_answer="Libya (until 2011)",
            category="Country Flags",
            difficulty="Easy",
        ),
        Question(
            text="What colors are on the flag of Russia?",
            correct_answer="White, blue, and red",
            category="Country Flags",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the largest ocean in the world?",
            correct_answer="Pacific Ocean",
            category="Oceans and Seas",
            difficulty="Easy",
        ),
        Question(
            text="Which ocean borders the east coast of the United States?",
            correct_answer="Atlantic Ocean",
            category="Oceans and Seas",
            difficulty="Intermediate",
        ),
        Question(
            text="What sea is between Europe and Africa?",
            correct_answer="Mediterranean Sea",
            category="Oceans and Seas",
            difficulty="Hard",
        ),
        Question(
            text="Which ocean surrounds Antarctica?",
            correct_answer="Southern Ocean",
            category="Oceans and Seas",
            difficulty="Easy",
        ),
        Question(
            text="What sea separates Saudi Arabia from Africa?",
            correct_answer="Red Sea",
            category="Oceans and Seas",
            difficulty="Hard",
        ),
        Question(
            text="Which sea lies between Australia and New Zealand?",
            correct_answer="Tasman Sea",
            category="Oceans and Seas",
            difficulty="Hard",
        ),
        Question(
            text="What is the smallest ocean in the world?",
            correct_answer="Arctic Ocean",
            category="Oceans and Seas",
            difficulty="Hard",
        ),
        Question(
            text="Which sea is known for its high salinity?",
            correct_answer="Dead Sea",
            category="Oceans and Seas",
            difficulty="Easy",
        ),
        Question(
            text="What ocean lies to the west of Africa?",
            correct_answer="Atlantic Ocean",
            category="Oceans and Seas",
            difficulty="Hard",
        ),
        Question(
            text="What is the name of the sea between Japan and Korea?",
            correct_answer="Sea of Japan",
            category="Oceans and Seas",
            difficulty="Easy",
        ),
        Question(
            text="Which sea is famous for its historical trade routes and pirates?",
            correct_answer="Caribbean Sea",
            category="Oceans and Seas",
            difficulty="Intermediate",
        ),
        Question(
            text="What sea is located between Ukraine and Turkey?",
            correct_answer="Black Sea",
            category="Oceans and Seas",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the warmest ocean?",
            correct_answer="Indian Ocean",
            category="Oceans and Seas",
            difficulty="Hard",
        ),
        Question(
            text="Which sea lies to the north of Russia?",
            correct_answer="Barents Sea",
            category="Oceans and Seas",
            difficulty="Hard",
        ),
        Question(
            text="What is the deepest part of the ocean called?",
            correct_answer="Mariana Trench",
            category="Oceans and Seas",
            difficulty="Intermediate",
        ),
        Question(
            text="What sea separates the United Kingdom from Norway?",
            correct_answer="North Sea",
            category="Oceans and Seas",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the name of the sea bordered by Eastern Europe, Western Asia, and the Caucasus?",
            correct_answer="Caspian Sea",
            category="Oceans and Seas",
            difficulty="Intermediate",
        ),
        Question(
            text="Which ocean is Bermuda located in?",
            correct_answer="Atlantic Ocean",
            category="Oceans and Seas",
            difficulty="Hard",
        ),
        Question(
            text="What sea is known for its oil reserves near the Middle East?",
            correct_answer="Persian Gulf",
            category="Oceans and Seas",
            difficulty="Intermediate",
        ),
        Question(
            text="Which sea lies between Greece and Turkey?",
            correct_answer="Aegean Sea",
            category="Oceans and Seas",
            difficulty="Easy",
        ),
        Question(
            text="Which country is known for sushi?",
            correct_answer="Japan",
            category="Cultural Foods",
            difficulty="Hard",
        ),
        Question(
            text="Where did pizza originate?",
            correct_answer="Italy",
            category="Cultural Foods",
            difficulty="Easy",
        ),
        Question(
            text="Which country is famous for tacos?",
            correct_answer="Mexico",
            category="Cultural Foods",
            difficulty="Intermediate",
        ),
        Question(
            text="From which country does the croissant originate?",
            correct_answer="France",
            category="Cultural Foods",
            difficulty="Easy",
        ),
        Question(
            text="What country is known for its pho soup?",
            correct_answer="Vietnam",
            category="Cultural Foods",
            difficulty="Easy",
        ),
        Question(
            text="Which country is famous for borscht?",
            correct_answer="Russia (and Eastern Europe)",
            category="Cultural Foods",
            difficulty="Intermediate",
        ),
        Question(
            text="Where did the dish paella originate?",
            correct_answer="Spain",
            category="Cultural Foods",
            difficulty="Easy",
        ),
        Question(
            text="Which country is known for maple syrup?",
            correct_answer="Canada",
            category="Cultural Foods",
            difficulty="Intermediate",
        ),
        Question(
            text="Where does the dish kimchi come from?",
            correct_answer="South Korea",
            category="Cultural Foods",
            difficulty="Easy",
        ),
        Question(
            text="In which country would you find bratwurst?",
            correct_answer="Germany",
            category="Cultural Foods",
            difficulty="Easy",
        ),
        Question(
            text="Which country is famous for couscous?",
            correct_answer="Morocco",
            category="Cultural Foods",
            difficulty="Easy",
        ),
        Question(
            text="What is the national dish of England?",
            correct_answer="Fish and chips",
            category="Cultural Foods",
            difficulty="Easy",
        ),
        Question(
            text="Which country is known for its barbecue tradition, especially brisket?",
            correct_answer="United States",
            category="Cultural Foods",
            difficulty="Hard",
        ),
        Question(
            text="What country is known for fondue?",
            correct_answer="Switzerland",
            category="Cultural Foods",
            difficulty="Intermediate",
        ),
        Question(
            text="From which country does the curry laksa come?",
            correct_answer="Malaysia",
            category="Cultural Foods",
            difficulty="Hard",
        ),
        Question(
            text="Where did hummus originate?",
            correct_answer="Middle East (various countries)",
            category="Cultural Foods",
            difficulty="Easy",
        ),
        Question(
            text="Which country is known for its tapas?",
            correct_answer="Spain",
            category="Cultural Foods",
            difficulty="Hard",
        ),
        Question(
            text="What country is famous for baklava?",
            correct_answer="Turkey (and Greece)",
            category="Cultural Foods",
            difficulty="Hard",
        ),
        Question(
            text="Which country is known for its Tom Yum soup?",
            correct_answer="Thailand",
            category="Cultural Foods",
            difficulty="Intermediate",
        ),
        Question(
            text="Where did chocolate originate?",
            correct_answer="Mexico",
            category="Cultural Foods",
            difficulty="Hard",
        ),
        Question(
            text="What is the national dish of Scotland?",
            correct_answer="Haggis",
            category="Cultural Foods",
            difficulty="Easy",
        ),
        Question(
            text="Which country is known for falafel?",
            correct_answer="Egypt (and Middle East)",
            category="Cultural Foods",
            difficulty="Intermediate",
        ),
        Question(
            text="Where did dim sum originate?",
            correct_answer="China",
            category="Cultural Foods",
            difficulty="Intermediate",
        ),
        Question(
            text="Which country is famous for its bratwurst sausages?",
            correct_answer="Germany",
            category="Cultural Foods",
            difficulty="Easy",
        ),
        Question(
            text="From which country does poutine originate?",
            correct_answer="Canada",
            category="Cultural Foods",
            difficulty="Easy",
        ),
        Question(
            text="Which country is known for green curry?",
            correct_answer="Thailand",
            category="Cultural Foods",
            difficulty="Intermediate",
        ),
        Question(
            text="Where is ceviche popular?",
            correct_answer="Peru",
            category="Cultural Foods",
            difficulty="Intermediate",
        ),
        Question(
            text="What country is known for its famous hotpot dish?",
            correct_answer="China",
            category="Cultural Foods",
            difficulty="Hard",
        ),
        Question(
            text="Which country is famous for its empanadas?",
            correct_answer="Argentina",
            category="Cultural Foods",
            difficulty="Intermediate",
        ),
        Question(
            text="Where did shawarma originate?",
            correct_answer="Middle East (various countries)",
            category="Cultural Foods",
            difficulty="Intermediate",
        ),
        Question(
            text="What country is known for pierogi?",
            correct_answer="Poland",
            category="Cultural Foods",
            difficulty="Easy",
        ),
        Question(
            text="Which country is known for schnitzel?",
            correct_answer="Austria",
            category="Cultural Foods",
            difficulty="Easy",
        ),
        Question(
            text="Where does the noodle dish ramen come from?",
            correct_answer="Japan",
            category="Cultural Foods",
            difficulty="Intermediate",
        ),
        Question(
            text="In which country would you find moussaka?",
            correct_answer="Greece",
            category="Cultural Foods",
            difficulty="Hard",
        ),
        Question(
            text="Which country is famous for its tortillas?",
            correct_answer="Mexico",
            category="Cultural Foods",
            difficulty="Intermediate",
        ),
        Question(
            text="Where did mole sauce originate?",
            correct_answer="Mexico",
            category="Cultural Foods",
            difficulty="Hard",
        ),
        Question(
            text="Which country is famous for its Wagyu beef?",
            correct_answer="Japan",
            category="Cultural Foods",
            difficulty="Hard",
        ),
        Question(
            text="Which country is known for tagine?",
            correct_answer="Morocco",
            category="Cultural Foods",
            difficulty="Easy",
        ),
        Question(
            text="From which country does churros originate?",
            correct_answer="Spain",
            category="Cultural Foods",
            difficulty="Easy",
        ),
        Question(
            text="Which country is known for its iconic crepes?",
            correct_answer="France",
            category="Cultural Foods",
            difficulty="Intermediate",
        ),
        Question(
            text="Where did the dish biryani originate?",
            correct_answer="India",
            category="Cultural Foods",
            difficulty="Intermediate",
        ),
        Question(
            text="In which country would you find naan bread?",
            correct_answer="India",
            category="Cultural Foods",
            difficulty="Intermediate",
        ),
        Question(
            text="Which country is known for its beef bourguignon?",
            correct_answer="France",
            category="Cultural Foods",
            difficulty="Intermediate",
        ),
        Question(
            text="What country is known for the dish jollof rice?",
            correct_answer="Nigeria (and West Africa)",
            category="Cultural Foods",
            difficulty="Hard",
        ),
        Question(
            text="Where does samosa originate?",
            correct_answer="India",
            category="Cultural Foods",
            difficulty="Intermediate",
        ),
        Question(
            text="Which country is known for its lamb kebabs?",
            correct_answer="Turkey",
            category="Cultural Foods",
            difficulty="Intermediate",
        ),
        Question(
            text="What country is famous for its stinky tofu?",
            correct_answer="Taiwan",
            category="Cultural Foods",
            difficulty="Hard",
        ),
        Question(
            text="Where did gazpacho originate?",
            correct_answer="Spain",
            category="Cultural Foods",
            difficulty="Intermediate",
        ),
        Question(
            text="Which country is known for feijoada?",
            correct_answer="Brazil",
            category="Cultural Foods",
            difficulty="Hard",
        ),
        Question(
            text="In which country would you find pandas in the wild?",
            correct_answer="China",
            category="Animal Habitats",
            difficulty="Easy",
        ),
        Question(
            text="Which continent is home to kangaroos?",
            correct_answer="Australia",
            category="Animal Habitats",
            difficulty="Hard",
        ),
        Question(
            text="What type of habitat do polar bears live in?",
            correct_answer="Arctic (cold, icy habitats)",
            category="Animal Habitats",
            difficulty="Hard",
        ),
        Question(
            text="Which animal is native to Madagascar?",
            correct_answer="Lemur",
            category="Animal Habitats",
            difficulty="Intermediate",
        ),
        Question(
            text="Where would you find lions in the wild?",
            correct_answer="Africa",
            category="Animal Habitats",
            difficulty="Hard",
        ),
        Question(
            text="Which habitat is home to most cacti?",
            correct_answer="Desert",
            category="Animal Habitats",
            difficulty="Easy",
        ),
        Question(
            text="Where do emperor penguins live?",
            correct_answer="Antarctica",
            category="Animal Habitats",
            difficulty="Hard",
        ),
        Question(
            text="In which country would you find Komodo dragons?",
            correct_answer="Indonesia",
            category="Animal Habitats",
            difficulty="Easy",
        ),
        Question(
            text="Where would you typically find a moose?",
            correct_answer="North America and Northern Europe",
            category="Animal Habitats",
            difficulty="Intermediate",
        ),
        Question(
            text="What type of habitat do alligators prefer?",
            correct_answer="Swamps and wetlands",
            category="Animal Habitats",
            difficulty="Intermediate",
        ),
        Question(
            text="What animal is native to the Galápagos Islands?",
            correct_answer="Galápagos tortoise",
            category="Animal Habitats",
            difficulty="Easy",
        ),
        Question(
            text="In which continent would you find elephants in the wild?",
            correct_answer="Africa and Asia",
            category="Animal Habitats",
            difficulty="Hard",
        ),
        Question(
            text="Which habitat is best suited for dolphins?",
            correct_answer="Ocean",
            category="Animal Habitats",
            difficulty="Easy",
        ),
        Question(
            text="Which animal is commonly found in the savanna?",
            correct_answer="Giraffe",
            category="Animal Habitats",
            difficulty="Intermediate",
        ),
        Question(
            text="Where would you find Siberian tigers?",
            correct_answer="Russia (Siberian forests)",
            category="Animal Habitats",
            difficulty="Hard",
        ),
        Question(
            text="What type of habitat is a coral reef?",
            correct_answer="Marine habitat (warm, shallow seas)",
            category="Animal Habitats",
            difficulty="Hard",
        ),
        Question(
            text="What habitat do camels primarily live in?",
            correct_answer="Desert",
            category="Animal Habitats",
            difficulty="Intermediate",
        ),
        Question(
            text="Where would you find wild orangutans?",
            correct_answer="Southeast Asia (Borneo and Sumatra)",
            category="Animal Habitats",
            difficulty="Hard",
        ),
        Question(
            text="Which animal is native to the Amazon rainforest?",
            correct_answer="Jaguar",
            category="Animal Habitats",
            difficulty="Easy",
        ),
        Question(
            text="Which continent is home to reindeer?",
            correct_answer="North America, Europe, and Asia (Arctic and subarctic regions)",
            category="Animal Habitats",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the official language of Brazil?",
            correct_answer="Portuguese",
            category="Languages of the World",
            difficulty="Hard",
        ),
        Question(
            text="In which country is Mandarin the official language?",
            correct_answer="China",
            category="Languages of the World",
            difficulty="Easy",
        ),
        Question(
            text="What language is primarily spoken in Austria?",
            correct_answer="German",
            category="Languages of the World",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the official language of Egypt?",
            correct_answer="Arabic",
            category="Languages of the World",
            difficulty="Easy",
        ),
        Question(
            text="Which language is primarily spoken in Argentina?",
            correct_answer="Spanish",
            category="Languages of the World",
            difficulty="Easy",
        ),
        Question(
            text="What is the official language of Japan?",
            correct_answer="Japanese",
            category="Languages of the World",
            difficulty="Hard",
        ),
        Question(
            text="What language is primarily spoken in Quebec, Canada?",
            correct_answer="French",
            category="Languages of the World",
            difficulty="Hard",
        ),
        Question(
            text="In which country is Swahili widely spoken?",
            correct_answer="Kenya and Tanzania",
            category="Languages of the World",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the official language of Russia?",
            correct_answer="Russian",
            category="Languages of the World",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the primary language spoken in Saudi Arabia?",
            correct_answer="Arabic",
            category="Languages of the World",
            difficulty="Hard",
        ),
        Question(
            text="Which language is spoken in Brazil, but not in most other South American countries?",
            correct_answer="Portuguese",
            category="Languages of the World",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the official language of Italy?",
            correct_answer="Italian",
            category="Languages of the World",
            difficulty="Easy",
        ),
        Question(
            text="Which language is primarily spoken in South Korea?",
            correct_answer="Korean",
            category="Languages of the World",
            difficulty="Hard",
        ),
        Question(
            text="What language is the most widely spoken in India?",
            correct_answer="Hindi",
            category="Languages of the World",
            difficulty="Easy",
        ),
        Question(
            text="What language do people speak in Greece?",
            correct_answer="Greek",
            category="Languages of the World",
            difficulty="Easy",
        ),
        Question(
            text="Which language is primarily spoken in the Netherlands?",
            correct_answer="Dutch",
            category="Languages of the World",
            difficulty="Hard",
        ),
        Question(
            text="What is the official language of Turkey?",
            correct_answer="Turkish",
            category="Languages of the World",
            difficulty="Easy",
        ),
        Question(
            text="What is the primary language spoken in Vietnam?",
            correct_answer="Vietnamese",
            category="Languages of the World",
            difficulty="Easy",
        ),
        Question(
            text="Which language is primarily spoken in Poland?",
            correct_answer="Polish",
            category="Languages of the World",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the official language of Israel?",
            correct_answer="Hebrew",
            category="Languages of the World",
            difficulty="Hard",
        ),
        Question(
            text="What is the tallest mountain in the world?",
            correct_answer="Mount Everest",
            category="Natural Wonders",
            difficulty="Intermediate",
        ),
        Question(
            text="Where is the Grand Canyon located?",
            correct_answer="Arizona, USA",
            category="Natural Wonders",
            difficulty="Intermediate",
        ),
        Question(
            text="Which river is the longest in the world?",
            correct_answer="The Nile River",
            category="Natural Wonders",
            difficulty="Hard",
        ),
        Question(
            text="What is the largest coral reef system in the world?",
            correct_answer="The Great Barrier Reef",
            category="Natural Wonders",
            difficulty="Hard",
        ),
        Question(
            text="Where is Victoria Falls located?",
            correct_answer="Border of Zambia and Zimbabwe",
            category="Natural Wonders",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the name of the largest desert in the world?",
            correct_answer="The Antarctic Desert",
            category="Natural Wonders",
            difficulty="Intermediate",
        ),
        Question(
            text="Which natural wonder is located in Australia and is sacred to Indigenous Australians?",
            correct_answer="Uluru (Ayers Rock)",
            category="Natural Wonders",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the largest rainforest in the world?",
            correct_answer="The Amazon Rainforest",
            category="Natural Wonders",
            difficulty="Intermediate",
        ),
        Question(
            text="Which geyser is famous in Yellowstone National Park?",
            correct_answer="Old Faithful",
            category="Natural Wonders",
            difficulty="Hard",
        ),
        Question(
            text="What is the name of the deepest part of the ocean?",
            correct_answer="The Mariana Trench",
            category="Natural Wonders",
            difficulty="Easy",
        ),
        Question(
            text="Which mountain range runs through Nepal and Bhutan?",
            correct_answer="The Himalayas",
            category="Natural Wonders",
            difficulty="Hard",
        ),
        Question(
            text="Where would you find the Marble Caves?",
            correct_answer="Chile and Argentina (Patagonia)",
            category="Natural Wonders",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the name of the famous salt flats in Bolivia?",
            correct_answer="Salar de Uyuni",
            category="Natural Wonders",
            difficulty="Easy",
        ),
        Question(
            text="Where are the Cliffs of Moher located?",
            correct_answer="Ireland",
            category="Natural Wonders",
            difficulty="Easy",
        ),
        Question(
            text="Which waterfall is located on the border of Canada and the USA?",
            correct_answer="Niagara Falls",
            category="Natural Wonders",
            difficulty="Intermediate",
        ),
        Question(
            text="What is the largest volcano on Earth?",
            correct_answer="Mauna Loa, Hawaii",
            category="Natural Wonders",
            difficulty="Intermediate",
        ),
        Question(
            text="Where is the famous Giant's Causeway located?",
            correct_answer="Northern Ireland",
            category="Natural Wonders",
            difficulty="Hard",
        ),
        Question(
            text="What is the name of the unique rock formations in Utah, USA?",
            correct_answer="Bryce Canyon",
            category="Natural Wonders",
            difficulty="Easy",
        ),
        Question(
            text="Which lake is known as the deepest in the world?",
            correct_answer="Lake Baikal",
            category="Natural Wonders",
            difficulty="Hard",
        ),
        Question(
            text="What is the name of the pink lake in Australia?",
            correct_answer="Lake Hillier",
            category="Natural Wonders",
            difficulty="Hard",
        ),
        Question(
            text="What is the largest country in the world by land area?",
            correct_answer="Russia",
            category="Global Trivia",
            difficulty="Easy",
        ),
        Question(
            text="Which country is known as the 'Land of the Rising Sun'?",
            correct_answer="Japan",
            category="Global Trivia",
            difficulty="Easy",
        ),
        Question(
            text="What continent is Egypt located in?",
            correct_answer="Africa",
            category="Global Trivia",
            difficulty="Easy",
        ),
        Question(
            text="What river flows through the city of Cairo?",
            correct_answer="Nile River",
            category="Natural Wonders",
            difficulty="Easy",
        ),
        Question(
            text="Which U.S. state is known as the 'Sunshine State'?",
            correct_answer="Florida",
            category="Global Trivia",
            difficulty="Easy",
        ),
        Question(
            text="What ocean lies on the east coast of the United States?",
            correct_answer="Atlantic Ocean",
            category="Natural Wonders",
            difficulty="Easy",
        ),
        Question(
            text="What is the smallest country in the world by land area?",
            correct_answer="Vatican City",
            category="Global Trivia",
            difficulty="Easy",
        ),
        Question(
            text="Which country is home to the Great Barrier Reef?",
            correct_answer="Australia",
            category="Global Trivia",
            difficulty="Easy",
        ),
        Question(
            text="What is the longest river in South America?",
            correct_answer="Amazon River",
            category="Natural Wonders",
            difficulty="Easy",
        ),
        Question(
            text="Which country is famous for its tulips and windmills?",
            correct_answer="Netherlands",
            category="Global Trivia",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital city of Japan?",
            correct_answer="Tokyo",
            category="Capital Cities",
            difficulty="Easy",
        ),
        Question(
            text="On which continent would you find the Sahara Desert?",
            correct_answer="Africa",
            category="Natural Wonders",
            difficulty="Easy",
        ),
        Question(
            text="What is the largest island in the world?",
            correct_answer="Greenland",
            category="Global Trivia",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital of Italy?",
            correct_answer="Rome",
            category="Capital Cities",
            difficulty="Easy",
        ),
        Question(
            text="Which country has the most people?",
            correct_answer="China",
            category="Global Trivia",
            difficulty="Easy",
        ),
        Question(
            text="What is the name of the tallest mountain in the world?",
            correct_answer="Mount Everest",
            category="Natural Wonders",
            difficulty="Easy",
        ),
        Question(
            text="What sea lies between Europe and Africa?",
            correct_answer="Mediterranean Sea",
            category="Natural Wonders",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital of England?",
            correct_answer="London",
            category="Capital Cities",
            difficulty="Easy",
        ),
        Question(
            text="Which country is known for the Eiffel Tower?",
            correct_answer="France",
            category="Famous Landmarks",
            difficulty="Easy",
        ),
        Question(
            text="What is the capital city of Spain?",
            correct_answer="Madrid",
            category="Capital Cities",
            difficulty="Easy",
        ),
        Question(
            text="Which U.S. state has the most islands?",
            correct_answer="Alaska",
            category="Global Trivia",
            difficulty="Easy",
        ),
        Question(
            text="What is the currency used in the United Kingdom?",
            correct_answer="Pound Sterling",
            category="Global Trivia",
            difficulty="Easy",
        ),
        Question(
            text="Which continent is both a country and a continent?",
            correct_answer="Australia",
            category="Global Trivia",
            difficulty="Easy",
        ),
        Question(
            text="What is the longest river in Europe?",
            correct_answer="The Volga River",
            category="Natural Wonders",
            difficulty="Medium",
        ),
        Question(
            text="Which desert covers most of northern Africa?",
            correct_answer="The Sahara Desert",
            category="Natural Wonders",
            difficulty="Medium",
        ),
        Question(
            text="What country is known for having the city of Reykjavik as its capital?",
            correct_answer="Iceland",
            category="Capital Cities",
            difficulty="Medium",
        ),
        Question(
            text="Which country is Mount Kilimanjaro located in?",
            correct_answer="Tanzania",
            category="Natural Wonders",
            difficulty="Medium",
        ),
        Question(
            text="Which river forms part of the border between the United States and Mexico?",
            correct_answer="The Rio Grande",
            category="Natural Wonders",
            difficulty="Medium",
        ),
        Question(
            text="What is the name of the ocean between Africa and Australia?",
            correct_answer="The Indian Ocean",
            category="Natural Wonders",
            difficulty="Medium",
        ),
        Question(
            text="Which South American country is landlocked?",
            correct_answer="Bolivia",
            category="Global Trivia",
            difficulty="Medium",
        ),
        Question(
            text="What is the largest lake in Africa?",
            correct_answer="Lake Victoria",
            category="Global Trivia",
            difficulty="Medium",
        ),
        Question(
            text="Which country has the most UNESCO World Heritage Sites?",
            correct_answer="Italy",
            category="Global Trivia",
            difficulty="Medium",
        ),
        Question(
            text="Which Asian country has the largest population?",
            correct_answer="China",
            category="Global Trivia",
            difficulty="Medium",
        ),
        Question(
            text="What is the currency used in Japan?",
            correct_answer="Yen",
            category="Global Trivia",
            difficulty="Medium",
        ),
        Question(
            text="What mountain range runs along the western edge of South America?",
            correct_answer="The Andes",
            category="Natural Wonders",
            difficulty="Medium",
        ),
        Question(
            text="What is the second largest country in the world by land area?",
            correct_answer="Canada",
            category="Global Trivia",
            difficulty="Medium",
        ),
        Question(
            text="Which country has the city of Casablanca?",
            correct_answer="Morocco",
            category="Global Trivia",
            difficulty="Medium",
        ),
        Question(
            text="Which river is the longest in the United Kingdom?",
            correct_answer="The River Severn",
            category="Natural Wonders",
            difficulty="Medium",
        ),
        Question(
            text="What country is home to the historic region of Transylvania?",
            correct_answer="Romania",
            category="Global Trivia",
            difficulty="Medium",
        ),
        Question(
            text="Which European country is known for the Black Forest?",
            correct_answer="Germany",
            category="Global Trivia",
            difficulty="Medium",
        ),
        Question(
            text="What is the name of the largest desert in Asia?",
            correct_answer="The Gobi Desert",
            category="Natural Wonders",
            difficulty="Medium",
        ),
        Question(
            text="What island country lies east of Mozambique in the Indian Ocean?",
            correct_answer="Madagascar",
            category="Natural Wonders",
            difficulty="Medium",
        ),
        Question(
            text="Which sea separates Saudi Arabia from Africa?",
            correct_answer="The Red Sea",
            category="Natural Wonders",
            difficulty="Medium",
        ),
        Question(
            text="What is the least populated country in the world?",
            correct_answer="Vatican City",
            category="Global Trivia",
            difficulty="Hard",
        ),
        Question(
            text="Which African country was formerly known as Abyssinia?",
            correct_answer="Ethiopia",
            category="Global Trivia",
            difficulty="Hard",
        ),
        Question(
            text="What is the capital of Bhutan?",
            correct_answer="Thimphu",
            category="Capital Cities",
            difficulty="Hard",
        ),
        Question(
            text="Which river flows through the most countries?",
            correct_answer="The Danube River",
            category="Natural Wonders",
            difficulty="Hard",
        ),
        Question(
            text="What is the official language of Suriname?",
            correct_answer="Dutch",
            category="Languages of the World",
            difficulty="Hard",
        ),
        Question(
            text="In which country can you find the ancient city of Petra?",
            correct_answer="Jordan",
            category="Global Trivia",
            difficulty="Hard",
        ),
        Question(
            text="Which country is home to the world’s oldest continuous monarchy?",
            correct_answer="Japan",
            category="Global Trivia",
            difficulty="Hard",
        ),
        Question(
            text="What is the capital of Burkina Faso?",
            correct_answer="Ouagadougou",
            category="Capital Cities",
            difficulty="Hard",
        ),
        Question(
            text="Which island is the second largest in the Mediterranean after Sicily?",
            correct_answer="Sardinia",
            category="Global Trivia",
            difficulty="Hard",
        ),
        Question(
            text="What is the highest point in North America?",
            correct_answer="Denali (Mount McKinley)",
            category="Global Trivia",
            difficulty="Hard",
        ),
        Question(
            text="Which South American country has both the Pacific and Atlantic Oceans as borders?",
            correct_answer="Colombia",
            category="Natural Wonders",
            difficulty="Hard",
        ),
        Question(
            text="What is the deepest lake in the world?",
            correct_answer="Lake Baikal",
            category="Global Trivia",
            difficulty="Hard",
        ),
        Question(
            text="Which Asian country has the longest coastline in the world?",
            correct_answer="Indonesia",
            category="Global Trivia",
            difficulty="Hard",
        ),
        Question(
            text="In what country is the historic site of Machu Picchu located?",
            correct_answer="Peru",
            category="Global Trivia",
            difficulty="Hard",
        ),
        Question(
            text="Which ocean is the warmest?",
            correct_answer="The Indian Ocean",
            category="Natural Wonders",
            difficulty="Hard",
        ),
        Question(
            text="What is the most populous city in Africa?",
            correct_answer="Lagos",
            category="Capital Cities",
            difficulty="Hard",
        ),
        Question(
            text="Which country has the most lakes in the world?",
            correct_answer="Canada",
            category="Global Trivia",
            difficulty="Hard",
        ),
        Question(
            text="What is the largest island in the Caribbean?",
            correct_answer="Cuba",
            category="Global Trivia",
            difficulty="Hard",
        ),
        Question(
            text="Which desert is the driest in the world?",
            correct_answer="The Atacama Desert",
            category="Natural Wonders",
            difficulty="Hard",
        ),
        Question(
            text="What country is home to the world's largest natural coral reef system?",
            correct_answer="Australia",
            category="Global Trivia",
            difficulty="Hard",
        ),
        Question(
            text="Which is the only country to have coastlines on both the Atlantic and Indian Oceans?",
            correct_answer="South Africa",
            category="Natural Wonders",
            difficulty="Hard",
        ),
        Question(
            text="What is the northernmost capital city in the world?",
            correct_answer="Reykjavik",
            category="Capital Cities",
            difficulty="Hard",
        ),
        Question(
            text="Which country has the longest national highway network?",
            correct_answer="The United States",
            category="Global Trivia",
            difficulty="Hard",
        ),
        Question(
            text="What is the southernmost city in the world?",
            correct_answer="Ushuaia, Argentina",
            category="Capital Cities",
            difficulty="Hard",
        ),
        Question(
            text="What country is home to Angel Falls, the world’s highest uninterrupted waterfall?",
            correct_answer="Venezuela",
            category="Global Trivia",
            difficulty="Hard",
        ),
    ]
    db.session.add_all(questions)
    db.session.commit()

    print("✅ Only questions seeded. Players, profiles, and sessions skipped.")
